package local:immediate-renderer;

interface types {
    variant event {
        modifiers(modifier-options),
        pointer(location),
        mouse-down(mouse-button),
        mouse-up(mouse-button),
        mouse-move,
        key-down(tuple<keys, key-options>),
        key-up(keys),
        request-composition-bounds(composition-bounds-req),
        update-composition-state(composition-state),
        history(history-ops),
        cut,
        copy,
        paste(string),
        activate,
        keep-focus,
    }

    variant unhandle-event {
        event(event),
        open-window(string),
    }

    record modifier-options {
        ctrl: modifier-pressed,
        shift: modifier-pressed,
        alt: modifier-pressed,
        super-key: modifier-pressed,
    }

    flags modifier-pressed {
        left,
        right,
    }

    record location {
        x: f32,
        y: f32,
    }

    enum mouse-button {
        left,
        right,
        middle,
        back,
        forward,
    }

    flags key-options {
        repeat,
    }

    variant keys {
        whitespace(whitespace-key),
        edit(edit-key),
        ui(ui-key),
        navi(navi-key),
    }

    enum whitespace-key {
        enter,
        tab,
        space,
    }

    enum edit-key {
        backspace,
        delete,
    }

    enum ui-key {
        escape,
    }

    enum navi-key {
        arrow-down,
        arrow-left,
        arrow-right,
        arrow-up,
        // end,
        // home,
        // page-down,
        // page-up,
    }

    enum history-ops {
        undo,
        redo,
    }

    variant composition-state {
        selection-range(composition-range),
        pre-edit(string),
        commit(string),
    }

    variant composition-bounds-req {
        character-bounds(option<composition-range>),
    }

    record composition-range {
        offset: u32,
        len: u32,
    }
}

world immediate-renderer-world {
    import local:webgpu-runtime/surface;
    export local:webgpu-runtime/surface;
    export types;
}
