import peer = globalThis;
export declare class GpuSupportedLimits {
    private readonly _handle;
    constructor(_handle: peer.GPUSupportedLimits);
    maxTextureDimension1D(): number;
    maxTextureDimension2D(): number;
    maxTextureDimension3D(): number;
    maxTextureArrayLayers(): number;
    maxBindGroups(): number;
    maxBindGroupsPlusVertexBuffers(): number;
    maxBindingsPerBindGroup(): number;
    maxDynamicUniformBuffersPerPipelineLayout(): number;
    maxDynamicStorageBuffersPerPipelineLayout(): number;
    maxSampledTexturesPerShaderStage(): number;
    maxSamplersPerShaderStage(): number;
    maxStorageBuffersPerShaderStage(): number;
    maxStorageTexturesPerShaderStage(): number;
    maxUniformBuffersPerShaderStage(): number;
    maxUniformBufferBindingSize(): bigint;
    maxStorageBufferBindingSize(): bigint;
    minUniformBufferOffsetAlignment(): number;
    minStorageBufferOffsetAlignment(): number;
    maxVertexBuffers(): number;
    maxBufferSize(): bigint;
    maxVertexAttributes(): number;
    maxVertexBufferArrayStride(): number;
    maxInterStageShaderVariables(): number;
    maxColorAttachments(): number;
    maxColorAttachmentBytesPerSample(): number;
    maxComputeWorkgroupStorageSize(): number;
    maxComputeInvocationsPerWorkgroup(): number;
    maxComputeWorkgroupSizeX(): number;
    maxComputeWorkgroupSizeY(): number;
    maxComputeWorkgroupSizeZ(): number;
    maxComputeWorkgroupsPerDimension(): number;
}
