import peer = globalThis;
import { poll } from "@bytecodealliance/preview2-shim/io";
import { Context } from "../wasi-graphics-context-graphics-context/context.js";
import { GpuAdapterInfo } from "./gpu-adapter-info.js";
import { GpuBindGroupLayout } from "./gpu-bind-group-layout.js";
import { GpuBindGroup } from "./gpu-bind-group.js";
import { GpuBuffer } from "./gpu-buffer.js";
import { GpuCommandEncoder } from "./gpu-command-encoder.js";
import { GpuComputePipeline } from "./gpu-compute-pipeline.js";
import { GpuDeviceLostInfo } from "./gpu-device-lost-info.js";
import { GpuError } from "./gpu-error.js";
import { GpuPipelineLayout } from "./gpu-pipeline-layout.js";
import { GpuQuerySet } from "./gpu-query-set.js";
import { GpuQueue } from "./gpu-queue.js";
import { GpuRenderBundleEncoder } from "./gpu-render-bundle-encoder.js";
import { GpuRenderPipeline } from "./gpu-render-pipeline.js";
import { GpuSampler } from "./gpu-sampler.js";
import { GpuShaderModule } from "./gpu-shader-module.js";
import { GpuSupportedFeatures } from "./gpu-supported-features.js";
import { GpuSupportedLimits } from "./gpu-supported-limits.js";
import { GpuTexture } from "./gpu-texture.js";
import type { GpuBindGroupDescriptor, GpuBindGroupLayoutDescriptor, GpuBufferDescriptor, GpuCommandEncoderDescriptor, GpuComputePipelineDescriptor, GpuErrorFilter, GpuPipelineLayoutDescriptor, GpuQuerySetDescriptor, GpuRenderBundleEncoderDescriptor, GpuRenderPipelineDescriptor, GpuSamplerDescriptor, GpuShaderModuleDescriptor, GpuTextureDescriptor } from "../../types/wasi-webgpu-webgpu.js";
export declare class GpuDevice {
    readonly _handle: peer.GPUDevice;
    constructor(_handle: peer.GPUDevice);
    features(): GpuSupportedFeatures;
    limits(): GpuSupportedLimits;
    adapterInfo(): GpuAdapterInfo;
    queue(): GpuQueue;
    destroy(): void;
    createBuffer(descriptor: GpuBufferDescriptor): GpuBuffer;
    createTexture(descriptor: GpuTextureDescriptor): GpuTexture;
    createSampler(descriptor: GpuSamplerDescriptor | undefined): GpuSampler;
    createBindGroupLayout(descriptor: GpuBindGroupLayoutDescriptor): GpuBindGroupLayout;
    createPipelineLayout(descriptor: GpuPipelineLayoutDescriptor): GpuPipelineLayout;
    createBindGroup(descriptor: GpuBindGroupDescriptor): GpuBindGroup;
    createShaderModule(descriptor: GpuShaderModuleDescriptor): GpuShaderModule;
    createComputePipeline(descriptor: GpuComputePipelineDescriptor): GpuComputePipeline;
    createRenderPipeline(descriptor: GpuRenderPipelineDescriptor): GpuRenderPipeline;
    createComputePipelineAsync(descriptor: GpuComputePipelineDescriptor): GpuComputePipeline;
    createRenderPipelineAsync(descriptor: GpuRenderPipelineDescriptor): GpuRenderPipeline;
    createCommandEncoder(descriptor: GpuCommandEncoderDescriptor | undefined): GpuCommandEncoder;
    createRenderBundleEncoder(descriptor: GpuRenderBundleEncoderDescriptor): GpuRenderBundleEncoder;
    createQuerySet(descriptor: GpuQuerySetDescriptor): GpuQuerySet;
    label(): string;
    setLabel(label: string): void;
    lost(): GpuDeviceLostInfo;
    pushErrorScope(filter: GpuErrorFilter): void;
    popErrorScope(): GpuError | undefined;
    onuncapturederrorSubscribe(): poll.Pollable;
    connectGraphicsContext(context: Context): void;
}
