import peer = globalThis;
import { GpuBindGroup } from "./gpu-bind-group.js";
import { GpuBuffer } from "./gpu-buffer.js";
import { GpuRenderBundle } from "./gpu-render-bundle.js";
import { GpuRenderPipeline } from "./gpu-render-pipeline.js";
import type { GpuColor, GpuIndex32, GpuIndexFormat, GpuIntegerCoordinate, GpuSignedOffset32, GpuSize32, GpuSize64, GpuStencilValue } from "../../types/wasi-webgpu-webgpu.js";
export declare class GpuRenderPassEncoder {
    private readonly _handle;
    constructor(_handle: peer.GPURenderPassEncoder);
    setViewport(x: number, y: number, width: number, height: number, minDepth: number, maxDepth: number): void;
    setScissorRect(x: GpuIntegerCoordinate, y: GpuIntegerCoordinate, width: GpuIntegerCoordinate, height: GpuIntegerCoordinate): void;
    setBlendConstant(color: GpuColor): void;
    setStencilReference(reference: GpuStencilValue): void;
    beginOcclusionQuery(queryIndex: GpuSize32): void;
    endOcclusionQuery(): void;
    executeBundles(bundles: Array<GpuRenderBundle>): void;
    end(): void;
    label(): string;
    setLabel(label: string): void;
    pushDebugGroup(groupLabel: string): void;
    popDebugGroup(): void;
    insertDebugMarker(markerLabel: string): void;
    setBindGroup(index: GpuIndex32, bindGroup: GpuBindGroup | undefined, dynamicOffsetsData: Uint32Array | undefined, dynamicOffsetsDataStart: GpuSize64 | undefined, dynamicOffsetsDataLength: GpuSize32 | undefined): void;
    setPipeline(pipeline: GpuRenderPipeline): void;
    setIndexBuffer(buffer: GpuBuffer, indexFormat: GpuIndexFormat, offset: GpuSize64 | undefined, size: GpuSize64 | undefined): void;
    setVertexBuffer(slot: GpuIndex32, buffer: GpuBuffer | undefined, offset: GpuSize64 | undefined, size: GpuSize64 | undefined): void;
    draw(vertexCount: GpuSize32, instanceCount: GpuSize32 | undefined, firstVertex: GpuSize32 | undefined, firstInstance: GpuSize32 | undefined): void;
    drawIndexed(indexCount: GpuSize32, instanceCount: GpuSize32 | undefined, firstIndex: GpuSize32 | undefined, baseVertex: GpuSignedOffset32 | undefined, firstInstance: GpuSize32 | undefined): void;
    drawIndirect(indirectBuffer: GpuBuffer, indirectOffset: GpuSize64): void;
    drawIndexedIndirect(indirectBuffer: GpuBuffer, indirectOffset: GpuSize64): void;
}
