package local:immediate-renderer-demo;

interface render {
    use local:webgpu-runtime/surface.{render-context};
    use local:immediate-renderer/types.{event};

    variant unhandle-event {
        event(event),
        open-window(string),
    }

    resource dispatcher {
        push-event: func(event: event);
        push-event-all: func(event: list<event>);
        dispatch: func() -> list<unhandle-event>;
    }

    create-main-renderer: func(context: render-context) -> dispatcher;
    create-triangle-renderer: func(context: render-context) -> dispatcher;
    create-counter-renderer: func(context: render-context) -> dispatcher;
}

world demo-world {
    import local:webgpu-runtime/surface;
    export render;
}
